API successfully returns data
rpt09-scully/profile-service pull request #3
Opened 2018-11-24 21:18 UTC by weber93

Also Updated README.

2018-11-26 01:16 UTC, MengRS commented
Pull request review in progress.  Stay tuned.

2018-11-26 01:33 UTC, MengRS reviewed
a small suggestion, the command `cp config-example.js config.js` does not work.  need to direct the user to cd to appropriate directory (in real life, in case the repos are so big - people may not find it unless they use a find command).

2018-11-26 01:47 UTC, MengRS commented
- [x] Pinged api (using port 3002), received exact data shape indicated on example-data.json
- [ ] [Still Reviewing] - reviewing schema.sql for 100 mock entries

2018-11-26 01:55 UTC, MengRS commented on README.md
> +  # setup config.js file (for sql creds)
```suggestion
  # setup config.js file (for sql creds), cd to `database-mysql`
```

2018-11-26 03:22 UTC, MengRS requested changes
Hey Matt, have some minor changes - take a look.

2018-11-26 03:22 UTC, MengRS commented on .gitignore
> +/database-mysql/config.js
Include node modules in here, since you directed npm install in `readme.md`.  This also helps your reviewer from loading a ton of changes in github.

2018-11-26 03:22 UTC, MengRS commented on schema.sql
> +  KEY `prof_act_fk0` (`act_id`),
curious what the `KEY` keyword does here (did some googling - does it refer to some sort of indexing function?)... I was expecting your junction table syntax to be something like [this](https://imgur.com/a/rlbfEZn) ([original link](https://www.mortenempeno.com/blog/sql-junction-tables/)).

 Your junction table seems to be working great - so this is just a question.

2018-12-01 19:13 UTC, weber93 commented
@MengRS Changes made.

2018-12-01 19:15 UTC, merged